definitions:
  config:
    /hst:hst/hst:configurations/gallerymagickdemo/hst:pages/newspage:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:containercomponentreference
        hst:referencecomponent: newspage/main
