definitions:
  config:
    /hippo:configuration/hippo:queries/hippo:templates/new-events-folder:
      jcr:primaryType: hippostd:templatequery
      jcr:mixinTypes: ['hipposys:implementation']
      hippostd:icon: addfolder_ico
      hippostd:modify: [./_name, $name, './hippotranslation:id', $uuid, './hippotranslation:locale',
        $inherited]
      hipposys:classname: org.hippoecm.repository.impl.query.DirectPath
      jcr:language: xpath
      jcr:statement: /jcr:root/hippo:configuration/hippo:queries/hippo:templates/new-events-folder/hippostd:templates/node()
      /hippostd:templates:
        jcr:primaryType: hippostd:templates
        /hippostd:folder:
          jcr:primaryType: hippostd:folder
          jcr:mixinTypes: ['hippotranslation:translated', 'mix:referenceable']
          jcr:uuid: a78016c1-689e-4c44-bee1-e68ffceb6cff
          hippostd:foldertype: [new-events-document, new-events-folder]
          hippotranslation:id: generated id
          hippotranslation:locale: inherited locale
